### ISSUE TITLE
NlqEcsBedrockStack.yaml refers to an incorrect Docker image tag

### ISSUE THREAD

**Issue by brnkrygs** [aws-solutions-library-samples/guidance-for-natural-language-queries-of-relational-databases-on-aws#46]
`NlqEcsBedrockStack.yaml` refers to a CloudFormation parameter `ECRImageTag` that has an incorrect value.

It currently refers to a tag value of `"1.0.5-bedrock"`. The actual tag in the build scripts and prior deployment steps is `"1.0.0-bedrock"`.

This tag needs to be fixed before the ECS services and tasks can be deployed.

**Comment by garystafford-aws** [comment]
Code merged to fix bug.
